- debug:
    msg: >-
      The names of the rules currently imported into the current play.
        role_name = {{ role_names }} 

      The path to the dir of the currently running role
        role_path = {{ role_path }}
