---
- hosts: webservers

  vars:
    oldskool: "1.2.3"
    bracket: "and close bracket"

  tasks:
  - command: echo hello world

  - name: trailing whitespace
    command: echo do nothing   

  - name: git check
    git: a=b c=d

  - name: git check 2
    git: version=HEAD c=d

  - name: git check 3
    git: version=a1b2c3d4 repo=xyz bobbins=d

  - name: executing git through command
    shell: git clone blah

  - name: executing git through command
    shell: chdir=bobbins creates=whatever /usr/bin/git clone blah

  - name: using git module
    action: git repo=blah

  - name: passing git as an argument to another task
    action: debug msg="{{item}}"
    with_items: 
      - git
      - bobbins

  - name: yum latest
    yum: state=latest name=httpd

  - debug: msg="task without a name"

  - name: apt latest
    apt: state=latest name=apache2

  - name: always run
    debug: msg="always_run is deprecated"
    always_run: true
