- name: Start VM
  hosts: localhost

  tasks:
  - name: Ensure VM is running
    vagrant_box:
      path: "{{ vagrantfile | mandatory }}"
      state: running
    register: vm

  - name: Update Inventory with newly created host
    add_host:
      name: playground
      hostname: "{{ vm.Host }}"
      ansible_host: "{{ vm.HostName }}"
      ansible_port: "{{ vm.Port }}"
      ansible_connection: "paramiko"
      ansible_user: "{{ vm.User }}"
      ansible_ssh_private_key_file: "{{ vm.IdentityFile }}"

- name: Provision Playground VM
  hosts: playground

  vars:
    system_info: |-
        Distributive: {{ ansible_distribution }}
        Family:       {{ ansible_distribution_file_variety }}
        Version:      {{ ansible_distribution_version }}

  pre_tasks:
  - debug: msg={{ system_info.split('\n') }}

  roles:
  - { role: base }
  - { role: nginx }
  - { role: tomcat, tomcat_release: 8.5.29 }


