- hosts: pull
  become: yes

  vars:

    # schedule is fed directly to cron
    schedule: '* * * * *'

    # User to run ansible-pull as from cron
    cron_user: root

    # File that ansible will use for logs
    logfile: /var/log/ansible-pull.log

    # Directory to where repository will be cloned
    workdir: /var/lib/ansible/local

    # Repository to check out -- YOU MUST CHANGE THIS
    # repo must contain a local.yml file at top level
    repo_url: git://github.com/sbeliakou/ansible-examples.git
    repo_branch: develop

    playbook: "trainings/day-5/tasks/pull/$(hostname -f).yml"

  tasks:
    - name: install yum-utils
      yum: name=yum-utils

    - name: install epel
      yum: name=epel-release

    - name: install git
      yum: name=git

    - name: install python-pip
      yum: name=python-pip

    - name: Install ansible
      pip: name=ansible

    - name: Create local directory to work from
      file: 
        path: "{{ workdir }}"
        state: directory
        owner: root
        group: root
        mode: 0751

    - cron:
        name: "asnible-pull"
        job: >-
          ASNIBLE_CONFIG={{ workdir }}/trainings/day-5/ansible.cfg
          ansible-pull 
          -U {{ repo_url }} 
          -C {{ repo_branch }} 
          -d {{ workdir }} 
          {{ playbook }} >> {{ logfile }} 2>&1
        user: root

    - name: Create logrotate entry for ansible-pull.log
      template: 
        src: templates/etc_logrotate.d_ansible-pull.j2
        dest: /etc/logrotate.d/ansible-pull
        owner: root
        group: root
        mode: 0644